server:
  port: 9527
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/brain_hole?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
      username: root
      password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml